name: flutterwhatsappclone
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8

environment:
  sdk: ">=2.12.0 <3.0.0"
#  sdk: ">=2.16.0 <3.0.0"
#  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  # intl_phone_number_input: ^0.7.0
  dashed_circle: ^0.0.2
  custom_switch: ^0.0.1
  shared_preferences: ^2.0.9
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  auto_size_text: ^3.0.0
  provider: ^6.0.2
  image_picker: ^0.8.4+11
  circular_profile_avatar: ^2.0.5
  cached_network_image: ^3.2.0
  file_picker: ^4.5.1
  toast: ^0.1.5
  cloud_firestore: ^3.1.7

#  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  google_sign_in: ^5.0.0
  firebase_auth: ^1.0.1
  firebase_database: ^6.1.0
  firebase_messaging: ^9.0.0
  firebase_storage: ^8.0.0
  flutter_screenutil: ^5.3.1
  timeago: ^3.2.2
  flutter_slidable: ^0.6.0
  flutter_spinkit: ^5.1.0
  video_player: ^2.3.0
  image_cropper: ^1.5.0
  inview_notifier_list: ^3.0.0
  photo_view: ^0.13.0
  contacts_service: ^0.6.3
  dio: ^4.0.4
  url_launcher: ^6.0.20
  # flutter_audio_recorder: ^0.5.5
#  audioplayers: ^0.16.0
  audioplayers: ^0.18.0
  flutter_countdown_timer: ^4.1.0
  permission_handler: ^9.2.0
  maps_launcher: ^2.0.1
  carousel_slider: ^4.0.0
#  screenshot:
  screenshot: ^1.2.3
  google_fonts: ^2.0.0
#  google_fonts: ^2.3.1
  agora_rtc_engine: ^5.0.1
  connectivity: ^3.0.6
  rflutter_alert: ^2.0.4
  percent_indicator: ^4.0.0
  video_compress: ^3.1.0
  flutter_image_compress: ^1.1.0
#  swipedetector:
  swipedetector: ^1.2.0
  flutter_linkify: ^5.0.2
  bubble: ^1.2.1
  linkable: ^3.0.1
  stop_watch_timer: ^1.3.1
  substring_highlight: ^1.0.33
  scroll_to_index: ^2.1.1
#  scroll_to_index:
#  multi_image_picker: ^4.8.0
  multi_image_picker2: ^5.0.2
  # flutter_absolute_path: ^1.0.6
  flutter_absolute_path: 
    git:
      url: https://github.com/canewsin/flutter_absolute_path.git
#  swipeable: ^1.1.0
  flutter_swipable: ^1.2.1
#  giphy_get:
  giphy_get: ^3.0.4
  share: ^2.0.4
  sn_progress_dialog: ^1.0.3
#  progress_dialog: ^1.2.1
  # image_editor_pro: 1.0.9
  flutter_local_notifications: ^9.4.0
#  flutter_local_notifications:
  # place_picker:
  flutter_chat_bubble: ^2.0.0
  visibility_detector: ^0.2.2
  country_code_picker: ^2.0.2
  dynamic_themes:



dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: "assets/images/applogo.png" 
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - data/

  fonts:
    - family: Montserrat  
      fonts:
        - asset: assets/fonts/Montserrat.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/MontserratBold.ttf
 

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
